
build: ./splay-tree/main.cpp ./treap/main.cpp
	@g++ -g -o ./splay-tree/main ./splay-tree/main.cpp
	@g++ -g -o ./treap/main ./treap/main.cpp

run1: ./splay-tree/main  
	@./splay-tree/main 

run2: ./treap/main
	@./treap/main 

clean:
	@rm -f ./splay-tree/main ./treap/main
