
build: ./segment-tree/main.cpp ./dynammic-segment-tree/main.cpp
	@g++ -g -o ./segment-tree/main ./segment-tree/main.cpp
	@g++ -g -o ./dynammic-segment-tree/main ./dynammic-segment-tree/main.cpp

run1: ./segment-tree/main  
	@./segment-tree/main 

run2: ./dynammic-segment-tree/main
	@./dynammic-segment-tree/main 

clean:
	@rm -f ./segment-tree/main ./dynammic-segment-tree/main
